"""Catálogo centralizado de instrumentos (fonte única de verdade).

Convenções (aproximadas, documentadas):
- `range`: [MIDI grave, MIDI agudo] em altura DE CONCERTO (som).
- `transposition`: semitons a SOMAR à nota escrita p/ obter o concerto
  (ex. trompete Bb = -2; instrumentos em concerto = 0).
- `midi_program`: programa General MIDI (0-127) quando aplicável;
  None p/ percussão indefinida/vozes (canal 10 ou sem programa).
- `pitched`: True (altura definida), False (indefinida), None (N/A).
"""

FAMILIES = [
    "woodwinds",
    "free_reed",
    "brass",
    "pitched_percussion",
    "unpitched_percussion",
    "body_percussion",
    "voices",
    "keyboards",
    "plucked_strings",
    "bowed_strings",
]

INSTRUMENTS = [
    # ---------------- MADEIRAS ----------------
    {"id": "piccolo", "name_pt": "Flautim", "name_en": "Piccolo", "family": "woodwinds",
     "subfamily": "flutes", "midi_program": 72, "transposition": 12, "clef": "treble",
     "range": [74, 108], "poly": False, "pitched": True, "aliases": ["piccolo", "flautim", "octavino"]},
    {"id": "flute", "name_pt": "Flauta", "name_en": "Flute", "family": "woodwinds",
     "subfamily": "flutes", "midi_program": 73, "transposition": 0, "clef": "treble",
     "range": [60, 96], "poly": False, "pitched": True, "aliases": ["flute", "flauta transversal", "flauta"]},
    {"id": "alto-flute", "name_pt": "Flauta alto", "name_en": "Alto flute", "family": "woodwinds",
     "subfamily": "flutes", "midi_program": 73, "transposition": -5, "clef": "treble",
     "range": [55, 91], "poly": False, "pitched": True, "aliases": ["alto flute"]},
    {"id": "bass-flute", "name_pt": "Flauta baixo", "name_en": "Bass flute", "family": "woodwinds",
     "subfamily": "flutes", "midi_program": 73, "transposition": -12, "clef": "treble",
     "range": [48, 84], "poly": False, "pitched": True, "aliases": ["bass flute"]},
    {"id": "recorder", "name_pt": "Flauta doce", "name_en": "Recorder", "family": "woodwinds",
     "subfamily": "recorders", "midi_program": 73, "transposition": 12, "clef": "treble",
     "range": [72, 98], "poly": False, "pitched": True, "aliases": ["recorder", "flauta doce", "blockflote"]},
    {"id": "oboe", "name_pt": "Oboé", "name_en": "Oboe", "family": "woodwinds",
     "subfamily": "double-reed", "midi_program": 68, "transposition": 0, "clef": "treble",
     "range": [58, 93], "poly": False, "pitched": True, "aliases": ["oboe", "oboe"]},
    {"id": "oboe-damore", "name_pt": "Oboé d'amore", "name_en": "Oboe d'amore", "family": "woodwinds",
     "subfamily": "double-reed", "midi_program": 68, "transposition": -3, "clef": "treble",
     "range": [56, 88], "poly": False, "pitched": True, "aliases": ["oboe d'amore"]},
    {"id": "english-horn", "name_pt": "Corne inglês", "name_en": "English horn", "family": "woodwinds",
     "subfamily": "double-reed", "midi_program": 69, "transposition": -7, "clef": "treble",
     "range": [52, 81], "poly": False, "pitched": True, "aliases": ["english horn", "cor anglais"]},
    {"id": "clarinet", "name_pt": "Clarinete", "name_en": "Clarinet", "family": "woodwinds",
     "subfamily": "single-reed", "midi_program": 71, "transposition": -2, "clef": "treble",
     "range": [52, 96], "poly": False, "pitched": True, "aliases": ["clarinet", "clarinete Bb"]},
    {"id": "alto-clarinet", "name_pt": "Clarinete alto", "name_en": "Alto clarinet", "family": "woodwinds",
     "subfamily": "single-reed", "midi_program": 71, "transposition": -9, "clef": "treble",
     "range": [51, 87], "poly": False, "pitched": True, "aliases": ["alto clarinet"]},
    {"id": "bass-clarinet", "name_pt": "Clarinete baixo", "name_en": "Bass clarinet", "family": "woodwinds",
     "subfamily": "single-reed", "midi_program": 71, "transposition": -14, "clef": "treble",
     "range": [34, 82], "poly": False, "pitched": True, "aliases": ["bass clarinet"]},
    {"id": "contrabass-clarinet", "name_pt": "Clarinete contrabaixo", "name_en": "Contrabass clarinet", "family": "woodwinds",
     "subfamily": "single-reed", "midi_program": 71, "transposition": -26, "clef": "bass",
     "range": [22, 70], "poly": False, "pitched": True, "aliases": ["contrabass clarinet"]},
    {"id": "bassoon", "name_pt": "Fagote", "name_en": "Bassoon", "family": "woodwinds",
     "subfamily": "double-reed", "midi_program": 70, "transposition": 0, "clef": "bass",
     "range": [34, 75], "poly": False, "pitched": True, "aliases": ["bassoon", "fagote"]},
    {"id": "contrabassoon", "name_pt": "Contrafagote", "name_en": "Contrabassoon", "family": "woodwinds",
     "subfamily": "double-reed", "midi_program": 70, "transposition": -12, "clef": "bass",
     "range": [22, 67], "poly": False, "pitched": True, "aliases": ["contrabassoon"]},
    {"id": "soprano-sax", "name_pt": "Saxofone soprano", "name_en": "Soprano saxophone", "family": "woodwinds",
     "subfamily": "saxophones", "midi_program": 64, "transposition": -2, "clef": "treble",
     "range": [56, 88], "poly": False, "pitched": True, "aliases": ["soprano sax"]},
    {"id": "alto-sax", "name_pt": "Saxofone alto", "name_en": "Alto saxophone", "family": "woodwinds",
     "subfamily": "saxophones", "midi_program": 65, "transposition": -9, "clef": "treble",
     "range": [49, 81], "poly": False, "pitched": True, "aliases": ["alto sax", "sax alto"]},
    {"id": "tenor-sax", "name_pt": "Saxofone tenor", "name_en": "Tenor saxophone", "family": "woodwinds",
     "subfamily": "saxophones", "midi_program": 66, "transposition": -14, "clef": "treble",
     "range": [45, 76], "poly": False, "pitched": True, "aliases": ["tenor sax", "sax tenor"]},
    {"id": "baritone-sax", "name_pt": "Saxofone barítono", "name_en": "Baritone saxophone", "family": "woodwinds",
     "subfamily": "saxophones", "midi_program": 67, "transposition": -21, "clef": "treble",
     "range": [38, 69], "poly": False, "pitched": True, "aliases": ["baritone sax", "bari sax"]},
    {"id": "bass-sax", "name_pt": "Saxofone baixo", "name_en": "Bass saxophone", "family": "woodwinds",
     "subfamily": "saxophones", "midi_program": 67, "transposition": -26, "clef": "bass",
     "range": [33, 64], "poly": False, "pitched": True, "aliases": ["bass sax"]},
    # ---------------- PALHETAS LIVRES ----------------
    {"id": "accordion", "name_pt": "Acordeão", "name_en": "Accordion", "family": "free_reed",
     "subfamily": "free-reed", "midi_program": 21, "transposition": 0, "clef": "grand",
     "range": [41, 93], "poly": True, "pitched": True, "aliases": ["accordion", "sanfona", "acordeon"]},
    {"id": "bandoneon", "name_pt": "Bandoneon", "name_en": "Bandoneon", "family": "free_reed",
     "subfamily": "free-reed", "midi_program": 21, "transposition": 0, "clef": "grand",
     "range": [45, 89], "poly": True, "pitched": True, "aliases": ["bandoneon", "bandoneón"]},
    {"id": "concertina", "name_pt": "Concertina", "name_en": "Concertina", "family": "free_reed",
     "subfamily": "free-reed", "midi_program": 21, "transposition": 0, "clef": "treble",
     "range": [55, 89], "poly": True, "pitched": True, "aliases": ["concertina"]},
    {"id": "harmonica", "name_pt": "Harmônica", "name_en": "Harmonica", "family": "free_reed",
     "subfamily": "free-reed", "midi_program": 22, "transposition": 0, "clef": "treble",
     "range": [60, 86], "poly": False, "pitched": True, "aliases": ["harmonica", "gaita de boca", "mouth organ", "blues harp"]},
    {"id": "bagpipes", "name_pt": "Gaita de foles", "name_en": "Bagpipes", "family": "free_reed",
     "subfamily": "free-reed", "midi_program": 109, "transposition": 0, "clef": "treble",
     "range": [62, 86], "poly": True, "pitched": True, "aliases": ["bagpipes", "gaita de foles", "gaita escocesa"]},
    # ---------------- METAIS ----------------
    {"id": "trumpet", "name_pt": "Trompete", "name_en": "Trumpet", "family": "brass",
     "subfamily": "high-brass", "midi_program": 56, "transposition": -2, "clef": "treble",
     "range": [54, 86], "poly": False, "pitched": True, "aliases": ["trumpet", "trompete Bb"]},
    {"id": "cornet", "name_pt": "Cornet", "name_en": "Cornet", "family": "brass",
     "subfamily": "high-brass", "midi_program": 56, "transposition": -2, "clef": "treble",
     "range": [54, 84], "poly": False, "pitched": True, "aliases": ["cornet", "cornetim"]},
    {"id": "flugelhorn", "name_pt": "Flugelhorn", "name_en": "Flugelhorn", "family": "brass",
     "subfamily": "high-brass", "midi_program": 56, "transposition": -2, "clef": "treble",
     "range": [54, 84], "poly": False, "pitched": True, "aliases": ["flugelhorn"]},
    {"id": "french-horn", "name_pt": "Trompa", "name_en": "French horn", "family": "brass",
     "subfamily": "mid-brass", "midi_program": 60, "transposition": -7, "clef": "treble",
     "range": [35, 77], "poly": False, "pitched": True, "aliases": ["french horn", "trompa", "corno"]},
    {"id": "trombone", "name_pt": "Trombone", "name_en": "Trombone", "family": "brass",
     "subfamily": "low-brass", "midi_program": 57, "transposition": 0, "clef": "bass",
     "range": [40, 77], "poly": False, "pitched": True, "aliases": ["trombone", "trombone de vara"]},
    {"id": "bass-trombone", "name_pt": "Trombone baixo", "name_en": "Bass trombone", "family": "brass",
     "subfamily": "low-brass", "midi_program": 57, "transposition": 0, "clef": "bass",
     "range": [34, 70], "poly": False, "pitched": True, "aliases": ["bass trombone"]},
    {"id": "euphonium", "name_pt": "Eufônio", "name_en": "Euphonium", "family": "brass",
     "subfamily": "low-brass", "midi_program": 58, "transposition": 0, "clef": "bass",
     "range": [34, 72], "poly": False, "pitched": True, "aliases": ["euphonium", "bombardino"]},
    {"id": "baritone-horn", "name_pt": "Barítono", "name_en": "Baritone horn", "family": "brass",
     "subfamily": "low-brass", "midi_program": 58, "transposition": 0, "clef": "bass",
     "range": [34, 72], "poly": False, "pitched": True, "aliases": ["baritone", "barítono"]},
    {"id": "tuba", "name_pt": "Tuba", "name_en": "Tuba", "family": "brass",
     "subfamily": "low-brass", "midi_program": 59, "transposition": 0, "clef": "bass",
     "range": [26, 65], "poly": False, "pitched": True, "aliases": ["tuba"]},
    {"id": "sousaphone", "name_pt": "Sousafone", "name_en": "Sousaphone", "family": "brass",
     "subfamily": "low-brass", "midi_program": 59, "transposition": 0, "clef": "bass",
     "range": [26, 65], "poly": False, "pitched": True, "aliases": ["sousaphone"]},
    # ---------------- PERCUSSÃO AFINADA ----------------
    {"id": "timpani", "name_pt": "Tímpano", "name_en": "Timpani", "family": "pitched_percussion",
     "subfamily": "membranophones-pitched", "midi_program": 47, "transposition": 0, "clef": "bass",
     "range": [38, 57], "poly": False, "pitched": True, "aliases": ["timpani", "tímpanos", "kettledrums"]},
    {"id": "marimba", "name_pt": "Marimba", "name_en": "Marimba", "family": "pitched_percussion",
     "subfamily": "mallet", "midi_program": 12, "transposition": 0, "clef": "grand",
     "range": [36, 96], "poly": True, "pitched": True, "aliases": ["marimba"]},
    {"id": "xylophone", "name_pt": "Xilofone", "name_en": "Xylophone", "family": "pitched_percussion",
     "subfamily": "mallet", "midi_program": 13, "transposition": 12, "clef": "treble",
     "range": [65, 108], "poly": True, "pitched": True, "aliases": ["xylophone", "xilofone"]},
    {"id": "vibraphone", "name_pt": "Vibrafone", "name_en": "Vibraphone", "family": "pitched_percussion",
     "subfamily": "mallet", "midi_program": 11, "transposition": 0, "clef": "grand",
     "range": [53, 89], "poly": True, "pitched": True, "aliases": ["vibraphone", "vibrafone", "vibes"]},
    {"id": "glockenspiel", "name_pt": "Glockenspiel", "name_en": "Glockenspiel", "family": "pitched_percussion",
     "subfamily": "mallet", "midi_program": 9, "transposition": 24, "clef": "treble",
     "range": [79, 108], "poly": False, "pitched": True, "aliases": ["glockenspiel", "carrilhão", "bells", "sino"]},
    {"id": "celesta", "name_pt": "Celesta", "name_en": "Celesta", "family": "pitched_percussion",
     "subfamily": "keyboard-percussion", "midi_program": 8, "transposition": 12, "clef": "treble",
     "range": [60, 108], "poly": True, "pitched": True, "aliases": ["celesta"]},
    {"id": "tubular-bells", "name_pt": "Tubular Bells", "name_en": "Tubular bells", "family": "pitched_percussion",
     "subfamily": "metal", "midi_program": 14, "transposition": 0, "clef": "treble",
     "range": [72, 77], "poly": False, "pitched": True, "aliases": ["tubular bells", "chimes", "sinos tubulares"]},
    {"id": "crotales", "name_pt": "Crotales", "name_en": "Crotales", "family": "pitched_percussion",
     "subfamily": "metal", "midi_program": 14, "transposition": 24, "clef": "treble",
     "range": [84, 108], "poly": False, "pitched": True, "aliases": ["crotales", "antique cymbals"]},
    # ---------------- PERCUSSÃO NÃO AFINADA ----------------
    {"id": "drum-kit", "name_pt": "Bateria", "name_en": "Drum kit", "family": "unpitched_percussion",
     "subfamily": "kit", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": True, "pitched": False, "aliases": ["drum kit", "bateria", "drums"]},
    {"id": "snare", "name_pt": "Caixa", "name_en": "Snare drum", "family": "unpitched_percussion",
     "subfamily": "membranes", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["snare", "caixa", "tarola"]},
    {"id": "kick", "name_pt": "Bumbo", "name_en": "Bass drum", "family": "unpitched_percussion",
     "subfamily": "membranes", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["kick", "bumbo", "bombo", "bass drum"]},
    {"id": "toms", "name_pt": "Tom-toms", "name_en": "Tom-toms", "family": "unpitched_percussion",
     "subfamily": "membranes", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": True, "pitched": False, "aliases": ["toms", "tons", "tom-tom"]},
    {"id": "hihat", "name_pt": "Hi-hat", "name_en": "Hi-hat", "family": "unpitched_percussion",
     "subfamily": "cymbals", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["hi-hat", "hihat", "chimbal"]},
    {"id": "crash", "name_pt": "Prato", "name_en": "Crash cymbal", "family": "unpitched_percussion",
     "subfamily": "cymbals", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["crash", "prato", "cymbal", "prato de ataque"]},
    {"id": "tambourine", "name_pt": "Pandeiro", "name_en": "Tambourine", "family": "unpitched_percussion",
     "subfamily": "hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["tambourine", "pandeiro"]},
    {"id": "triangle", "name_pt": "Triângulo", "name_en": "Triangle", "family": "unpitched_percussion",
     "subfamily": "metal-hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["triangle", "triângulo"]},
    {"id": "cowbell", "name_pt": "Cowbell", "name_en": "Cowbell", "family": "unpitched_percussion",
     "subfamily": "metal-hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["cowbell"]},
    {"id": "castanets", "name_pt": "Castanholas", "name_en": "Castanets", "family": "unpitched_percussion",
     "subfamily": "hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["castanets", "castanholas"]},
    {"id": "shaker", "name_pt": "Shaker", "name_en": "Shaker", "family": "unpitched_percussion",
     "subfamily": "hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["shaker", "chocalho", "ganza"]},
    {"id": "claves", "name_pt": "Claves", "name_en": "Claves", "family": "unpitched_percussion",
     "subfamily": "wood", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["claves"]},
    {"id": "woodblock", "name_pt": "Woodblock", "name_en": "Woodblock", "family": "unpitched_percussion",
     "subfamily": "wood", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["woodblock", "bloco de madeira"]},
    {"id": "tamborim", "name_pt": "Tamborim", "name_en": "Tamborim", "family": "unpitched_percussion",
     "subfamily": "hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["tamborim"]},
    {"id": "bongos", "name_pt": "Bongôs", "name_en": "Bongos", "family": "unpitched_percussion",
     "subfamily": "hand-drums", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": True, "pitched": False, "aliases": ["bongos", "bongô"]},
    {"id": "congas", "name_pt": "Congas", "name_en": "Congas", "family": "unpitched_percussion",
     "subfamily": "hand-drums", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": True, "pitched": False, "aliases": ["congas", "tumbadoras", "atabaque"]},
    {"id": "timbales", "name_pt": "Timbales", "name_en": "Timbales", "family": "unpitched_percussion",
     "subfamily": "hand-drums", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": True, "pitched": False, "aliases": ["timbales", "timbalitos"]},
    {"id": "djembe", "name_pt": "Djembê", "name_en": "Djembe", "family": "unpitched_percussion",
     "subfamily": "hand-drums", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["djembe", "djembê", "jembe"]},
    {"id": "cajon", "name_pt": "Cajón", "name_en": "Cajon", "family": "unpitched_percussion",
     "subfamily": "hand-drums", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["cajon", "cajón", "caixon"]},
    {"id": "surdo", "name_pt": "Surdo", "name_en": "Surdo", "family": "unpitched_percussion",
     "subfamily": "membranes", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["surdo"]},
    {"id": "agogo", "name_pt": "Agogô", "name_en": "Agogo", "family": "unpitched_percussion",
     "subfamily": "metal-hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["agogo", "agogô"]},
    {"id": "reco-reco", "name_pt": "Reco-reco", "name_en": "Reco-reco", "family": "unpitched_percussion",
     "subfamily": "scraper", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["reco-reco", "guiro", "raspador"]},
    {"id": "maracas", "name_pt": "Maracas", "name_en": "Maracas", "family": "unpitched_percussion",
     "subfamily": "hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["maracas"]},
    {"id": "cabasa", "name_pt": "Cabasa", "name_en": "Cabasa", "family": "unpitched_percussion",
     "subfamily": "hand", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["cabasa", "cabaça", "afuche"]},
    # ---------------- PERCUSSÃO CORPORAL ----------------
    {"id": "claps", "name_pt": "Palmas", "name_en": "Hand claps", "family": "body_percussion",
     "subfamily": "hands", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": True, "pitched": False, "aliases": ["claps", "palmas", "handclaps"]},
    {"id": "finger-snaps", "name_pt": "Estalos de dedos", "name_en": "Finger snaps", "family": "body_percussion",
     "subfamily": "hands", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["snaps", "estalos", "estalidos"]},
    {"id": "stomps", "name_pt": "Batidas de pé", "name_en": "Stomps", "family": "body_percussion",
     "subfamily": "feet", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["stomps", "batidas de pé", "pisadas"]},
    {"id": "chest-slap", "name_pt": "Chest slap", "name_en": "Chest slap", "family": "body_percussion",
     "subfamily": "torso", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["chest slap"]},
    {"id": "vocal-beatbox", "name_pt": "Beatbox", "name_en": "Beatbox", "family": "body_percussion",
     "subfamily": "vocal", "midi_program": None, "transposition": 0, "clef": "percussion",
     "range": None, "poly": False, "pitched": False, "aliases": ["beatbox", "vocal percussion"]},
    # ---------------- VOZES ----------------
    {"id": "lead-vocal", "name_pt": "Voz principal", "name_en": "Lead vocal", "family": "voices",
     "subfamily": "generic", "midi_program": 52, "transposition": 0, "clef": "treble",
     "range": [48, 84], "poly": False, "pitched": True, "aliases": ["lead vocal", "voz principal", "voz", "vocal", "lead vocals"]},
    {"id": "soprano", "name_pt": "Soprano", "name_en": "Soprano voice", "family": "voices",
     "subfamily": "female", "midi_program": 52, "transposition": 0, "clef": "treble",
     "range": [60, 81], "poly": False, "pitched": True, "aliases": ["soprano"]},
    {"id": "mezzo-soprano", "name_pt": "Mezzo-soprano", "name_en": "Mezzo-soprano voice", "family": "voices",
     "subfamily": "female", "midi_program": 52, "transposition": 0, "clef": "treble",
     "range": [57, 81], "poly": False, "pitched": True, "aliases": ["mezzo", "mezzo-soprano"]},
    {"id": "contralto", "name_pt": "Contralto", "name_en": "Contralto voice", "family": "voices",
     "subfamily": "female", "midi_program": 52, "transposition": 0, "clef": "treble",
     "range": [53, 77], "poly": False, "pitched": True, "aliases": ["contralto", "alto vocal"]},
    {"id": "tenor-voice", "name_pt": "Tenor", "name_en": "Tenor voice", "family": "voices",
     "subfamily": "male", "midi_program": 52, "transposition": 0, "clef": "treble",
     "range": [48, 69], "poly": False, "pitched": True, "aliases": ["tenor"]},
    {"id": "baritone-voice", "name_pt": "Barítono (voz)", "name_en": "Baritone voice", "family": "voices",
     "subfamily": "male", "midi_program": 52, "transposition": 0, "clef": "bass",
     "range": [43, 67], "poly": False, "pitched": True, "aliases": ["baritone voice"]},
    {"id": "bass-voice", "name_pt": "Baixo (voz)", "name_en": "Bass voice", "family": "voices",
     "subfamily": "male", "midi_program": 52, "transposition": 0, "clef": "bass",
     "range": [40, 64], "poly": False, "pitched": True, "aliases": ["bass voice", "baixo vocal"]},
    {"id": "female-voice", "name_pt": "Voz feminina", "name_en": "Female voice", "family": "voices",
     "subfamily": "generic", "midi_program": 52, "transposition": 0, "clef": "treble",
     "range": [53, 81], "poly": False, "pitched": True, "aliases": ["female voice", "voz feminina"]},
    {"id": "male-voice", "name_pt": "Voz masculina", "name_en": "Male voice", "family": "voices",
     "subfamily": "generic", "midi_program": 52, "transposition": 0, "clef": "bass",
     "range": [40, 69], "poly": False, "pitched": True, "aliases": ["male voice", "voz masculina"]},
    {"id": "child-voice", "name_pt": "Voz infantil", "name_en": "Child voice", "family": "voices",
     "subfamily": "generic", "midi_program": 52, "transposition": 0, "clef": "treble",
     "range": [65, 86], "poly": False, "pitched": True, "aliases": ["child voice", "voz infantil", "voz aguda"]},
    {"id": "choir-satb", "name_pt": "Coro SATB", "name_en": "SATB choir", "family": "voices",
     "subfamily": "choir", "midi_program": 52, "transposition": 0, "clef": "grand",
     "range": [40, 81], "poly": True, "pitched": True, "aliases": ["satb", "coro satb", "choir"]},
    {"id": "choir-mixed", "name_pt": "Coro misto", "name_en": "Mixed choir", "family": "voices",
     "subfamily": "choir", "midi_program": 52, "transposition": 0, "clef": "grand",
     "range": [40, 84], "poly": True, "pitched": True, "aliases": ["mixed choir", "coro misto", "coral"]},
    # ---------------- TECLADOS ----------------
    {"id": "piano", "name_pt": "Piano", "name_en": "Piano", "family": "keyboards",
     "subfamily": "struck", "midi_program": 0, "transposition": 0, "clef": "grand",
     "range": [21, 108], "poly": True, "pitched": True, "aliases": ["piano", "pianoforte"]},
    {"id": "electric-piano", "name_pt": "Piano elétrico", "name_en": "Electric piano", "family": "keyboards",
     "subfamily": "electro-mechanical", "midi_program": 4, "transposition": 0, "clef": "grand",
     "range": [28, 88], "poly": True, "pitched": True, "aliases": ["electric piano", "rhodes", "wurlitzer", "piano elétrico"]},
    {"id": "organ", "name_pt": "Órgão", "name_en": "Organ", "family": "keyboards",
     "subfamily": "wind", "midi_program": 16, "transposition": 0, "clef": "grand",
     "range": [36, 96], "poly": True, "pitched": True, "aliases": ["organ", "órgão"]},
    {"id": "hammond-organ", "name_pt": "Órgão Hammond", "name_en": "Hammond organ", "family": "keyboards",
     "subfamily": "electro-mechanical", "midi_program": 16, "transposition": 0, "clef": "grand",
     "range": [36, 96], "poly": True, "pitched": True, "aliases": ["hammond", "órgão hammond"]},
    {"id": "pipe-organ", "name_pt": "Órgão de tubos", "name_en": "Pipe organ", "family": "keyboards",
     "subfamily": "wind", "midi_program": 19, "transposition": 0, "clef": "grand",
     "range": [24, 96], "poly": True, "pitched": True, "aliases": ["pipe organ", "órgão de tubos"]},
    {"id": "clavichord", "name_pt": "Clavicórdio", "name_en": "Clavichord", "family": "keyboards",
     "subfamily": "struck", "midi_program": 7, "transposition": 0, "clef": "grand",
     "range": [41, 86], "poly": True, "pitched": True, "aliases": ["clavichord", "clavicórdio"]},
    {"id": "harpsichord", "name_pt": "Cravo", "name_en": "Harpsichord", "family": "keyboards",
     "subfamily": "plucked-keys", "midi_program": 6, "transposition": 0, "clef": "grand",
     "range": [29, 89], "poly": True, "pitched": True, "aliases": ["harpsichord", "cravo", "cembalo"]},
    {"id": "synthesizer", "name_pt": "Sintetizador", "name_en": "Synthesizer", "family": "keyboards",
     "subfamily": "electronic", "midi_program": 80, "transposition": 0, "clef": "grand",
     "range": [21, 108], "poly": True, "pitched": True, "aliases": ["synthesizer", "synth", "sintetizador", "teclado"]},
    {"id": "keyboard", "name_pt": "Teclado", "name_en": "Keyboard", "family": "keyboards",
     "subfamily": "electronic", "midi_program": 80, "transposition": 0, "clef": "grand",
     "range": [21, 108], "poly": True, "pitched": True, "aliases": ["keyboard", "teclado eletrônico"]},
    # ---------------- CORDAS DEDILHADAS ----------------
    {"id": "classical-guitar", "name_pt": "Violão clássico", "name_en": "Classical guitar", "family": "plucked_strings",
     "subfamily": "guitars", "midi_program": 24, "transposition": -12, "clef": "treble",
     "range": [40, 88], "poly": True, "pitched": True, "aliases": ["classical guitar", "violão clássico", "violão nylon", "spanish guitar"]},
    {"id": "acoustic-guitar", "name_pt": "Violão acústico", "name_en": "Acoustic guitar", "family": "plucked_strings",
     "subfamily": "guitars", "midi_program": 25, "transposition": -12, "clef": "treble",
     "range": [40, 88], "poly": True, "pitched": True, "aliases": ["acoustic guitar", "violão acústico", "violão", "folk guitar"]},
    {"id": "steel-guitar", "name_pt": "Violão de aço", "name_en": "Steel-string guitar", "family": "plucked_strings",
     "subfamily": "guitars", "midi_program": 25, "transposition": -12, "clef": "treble",
     "range": [40, 88], "poly": True, "pitched": True, "aliases": ["steel guitar", "violão de aço"]},
    {"id": "twelve-string-guitar", "name_pt": "Violão de 12 cordas", "name_en": "12-string guitar", "family": "plucked_strings",
     "subfamily": "guitars", "midi_program": 25, "transposition": -12, "clef": "treble",
     "range": [40, 88], "poly": True, "pitched": True, "aliases": ["12-string", "violão 12 cordas"]},
    {"id": "electric-guitar", "name_pt": "Guitarra elétrica", "name_en": "Electric guitar", "family": "plucked_strings",
     "subfamily": "guitars", "midi_program": 27, "transposition": -12, "clef": "treble",
     "range": [40, 88], "poly": True, "pitched": True, "aliases": ["electric guitar", "guitarra elétrica", "guitarra"]},
    {"id": "electric-bass", "name_pt": "Baixo elétrico", "name_en": "Electric bass", "family": "plucked_strings",
     "subfamily": "bass-guitars", "midi_program": 33, "transposition": -12, "clef": "bass",
     "range": [28, 67], "poly": True, "pitched": True, "aliases": ["electric bass", "baixo elétrico", "baixo", "bass guitar"]},
    {"id": "upright-electric-bass", "name_pt": "Contrabaixo elétrico", "name_en": "Upright electric bass", "family": "plucked_strings",
     "subfamily": "bass-guitars", "midi_program": 33, "transposition": -12, "clef": "bass",
     "range": [28, 67], "poly": False, "pitched": True, "aliases": ["contrabaixo elétrico"]},
    {"id": "ukulele", "name_pt": "Ukulele", "name_en": "Ukulele", "family": "plucked_strings",
     "subfamily": "small", "midi_program": 24, "transposition": 0, "clef": "treble",
     "range": [60, 81], "poly": True, "pitched": True, "aliases": ["ukulele", "ukelele"]},
    {"id": "banjo", "name_pt": "Banjo", "name_en": "Banjo", "family": "plucked_strings",
     "subfamily": "small", "midi_program": 105, "transposition": 0, "clef": "treble",
     "range": [55, 86], "poly": True, "pitched": True, "aliases": ["banjo"]},
    {"id": "mandolin", "name_pt": "Bandolim", "name_en": "Mandolin", "family": "plucked_strings",
     "subfamily": "small", "midi_program": 25, "transposition": 0, "clef": "treble",
     "range": [55, 88], "poly": True, "pitched": True, "aliases": ["mandolin", "bandolim"]},
    {"id": "harp", "name_pt": "Harpa", "name_en": "Harp", "family": "plucked_strings",
     "subfamily": "harps", "midi_program": 46, "transposition": 0, "clef": "grand",
     "range": [23, 102], "poly": True, "pitched": True, "aliases": ["harp", "harpa"]},
    {"id": "lute", "name_pt": "Alaúde", "name_en": "Lute", "family": "plucked_strings",
     "subfamily": "historical", "midi_program": 24, "transposition": -12, "clef": "treble",
     "range": [40, 76], "poly": True, "pitched": True, "aliases": ["lute", "alaúde"]},
    {"id": "sitar", "name_pt": "Sitar", "name_en": "Sitar", "family": "plucked_strings",
     "subfamily": "world", "midi_program": 104, "transposition": 0, "clef": "treble",
     "range": [48, 84], "poly": True, "pitched": True, "aliases": ["sitar", "cítara indiana"]},
    {"id": "balalaika", "name_pt": "Balalaika", "name_en": "Balalaika", "family": "plucked_strings",
     "subfamily": "world", "midi_program": 25, "transposition": 0, "clef": "treble",
     "range": [55, 81], "poly": True, "pitched": True, "aliases": ["balalaika", "balalaica"]},
    {"id": "cavaquinho", "name_pt": "Cavaquinho", "name_en": "Cavaquinho", "family": "plucked_strings",
     "subfamily": "small", "midi_program": 25, "transposition": 0, "clef": "treble",
     "range": [62, 86], "poly": True, "pitched": True, "aliases": ["cavaquinho", "cavaco", "machete"]},
    # ---------------- CORDAS FRICCIONADAS ----------------
    {"id": "violin", "name_pt": "Violino", "name_en": "Violin", "family": "bowed_strings",
     "subfamily": "violin-family", "midi_program": 40, "transposition": 0, "clef": "treble",
     "range": [55, 93], "poly": False, "pitched": True, "aliases": ["violin", "violino", "fiddle"]},
    {"id": "viola", "name_pt": "Viola", "name_en": "Viola", "family": "bowed_strings",
     "subfamily": "violin-family", "midi_program": 41, "transposition": 0, "clef": "alto",
     "range": [48, 88], "poly": False, "pitched": True, "aliases": ["viola", "viola de arco"]},
    {"id": "cello", "name_pt": "Violoncelo", "name_en": "Cello", "family": "bowed_strings",
     "subfamily": "violin-family", "midi_program": 42, "transposition": 0, "clef": "bass",
     "range": [36, 84], "poly": False, "pitched": True, "aliases": ["cello", "violoncelo", "violoncello"]},
    {"id": "double-bass", "name_pt": "Contrabaixo", "name_en": "Double bass", "family": "bowed_strings",
     "subfamily": "violin-family", "midi_program": 43, "transposition": -12, "clef": "bass",
     "range": [28, 67], "poly": False, "pitched": True, "aliases": ["double bass", "contrabaixo", "contrabaixo acústico", "string bass"]},
    {"id": "electric-violin", "name_pt": "Violino elétrico", "name_en": "Electric violin", "family": "bowed_strings",
     "subfamily": "electric", "midi_program": 40, "transposition": 0, "clef": "treble",
     "range": [55, 93], "poly": False, "pitched": True, "aliases": ["electric violin"]},
    {"id": "electric-viola", "name_pt": "Viola elétrica", "name_en": "Electric viola", "family": "bowed_strings",
     "subfamily": "electric", "midi_program": 41, "transposition": 0, "clef": "alto",
     "range": [48, 88], "poly": False, "pitched": True, "aliases": ["electric viola"]},
    {"id": "electric-cello", "name_pt": "Violoncelo elétrico", "name_en": "Electric cello", "family": "bowed_strings",
     "subfamily": "electric", "midi_program": 42, "transposition": 0, "clef": "bass",
     "range": [36, 84], "poly": False, "pitched": True, "aliases": ["electric cello"]},
]


def _index():
    by_id = {}
    for inst in INSTRUMENTS:
        by_id[inst["id"]] = inst
    return by_id


BY_ID = _index()


# IDs alcançáveis pelo classificador neural (ver 3F; sincronia testada
# contra o mapeamento — não editar à mão sem atualizar o teste).
_MODEL_SUPPORTED = frozenset([
    "piano", "electric-piano", "organ", "hammond-organ", "harpsichord",
    "synthesizer", "acoustic-guitar", "electric-guitar", "electric-bass",
    "double-bass", "violin", "cello", "drum-kit", "snare", "hihat",
    "crash", "timpani", "tambourine", "maracas", "flute", "alto-sax",
    "tenor-sax", "clarinet", "harp", "accordion", "harmonica",
    "bagpipes", "trombone", "trumpet", "french-horn", "marimba",
    "xylophone", "vibraphone", "sitar", "ukulele", "banjo", "mandolin",
    "lead-vocal", "choir-mixed",
])

for _inst in INSTRUMENTS:
    _inst["model_supported"] = _inst["id"] in _MODEL_SUPPORTED
del _inst


def get(instrument_id):
    """Devolve o instrumento ou None."""
    return BY_ID.get(instrument_id)


def by_family(family):
    """Todos os instrumentos de uma família."""
    return [i for i in INSTRUMENTS if i["family"] == family]


def search(term):
    """Busca case-insensitive em nomes e aliases."""
    needle = term.strip().lower()
    if not needle:
        return []
    out = []
    for inst in INSTRUMENTS:
        hay = [inst["name_pt"], inst["name_en"]] + list(inst["aliases"])
        if any(needle in h.lower() for h in hay):
            out.append(inst)
    return out


def export_json(path):
    """Exporta o catálogo para JSON (uso futuro PHP/JS)."""
    import json
    with open(path, "w", encoding="utf-8") as fh:
        json.dump({"families": FAMILIES, "instruments": INSTRUMENTS},
                  fh, ensure_ascii=False, indent=1)
    return path
